platform :ios, '7.0' 
target :HBS_C do

pod 'AFNetworking', '~> 3.1.0'
pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'Masonry', '~> 1.0.1’
pod 'SDWebImage', '~> 3.7.3'
pod 'MJRefresh', '~> 3.0.4'

end